FROM node:alpine

# set working directory
WORKDIR '/app'                            

# the package.json to working directory
COPY package.json .    
RUN npm install

# copy everything to the working directory
COPY . .

CMD ["npm", "run", "start"]








# command ------------------------------------
# --------------------------------------------


# docker build .                        ## we cant use this for docker file withd custom name, e.g. Dockerfile.dev (instead of Dockerfile)
# docker build -f Dockerfile.dev .      ## build docker image, -f => specify the name of hte docker file