version: '3'
services:
  web:
    # we need this because of the bug in create-react-app
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      # bookmark a folder and not to reference it to any folder in host (outside the container)
      - /app/node_modules
      - .:/app



## Command ------------------------------------------
## --------------------------------------------------

# 0676 - Shorthand with Docker Compose
## docker-compose up              # not working, because of customer docker file name, i.e. Dockerfile.dev

# 0677 - Overriding DockerFile selection
## docker-compose up              # working this time


# 0681 - live updating tests - run test inside the container in which the reference are all set up
# start a docker container from a compose file and then exec command inside that container
## docker exec -it CONTAINER_ID(docker compose, not docker file) npm run test 
